Mui form
proga-react-practice/alpha-viktoria-osoba pull request #2
Opened 2024-04-28 15:38 UTC by Feevicun

<img width="1229" alt="Screenshot 2024-04-28 at 18 38 09" src="https://github.com/proga-react-practice/alpha-viktoria-osoba/assets/121824657/b0a7b3aa-c2fc-42ab-884e-b4f43c3a76eb">

<img width="1229" alt="Screenshot 2024-04-28 at 18 38 22" src="https://github.com/proga-react-practice/alpha-viktoria-osoba/assets/121824657/5639d611-baef-4b8e-9eb3-7708aae533c6">

2024-04-29 17:56 UTC, yak0vliev requested changes
Form looks great, good job!
But why did you move your project to the another folder? A little bit hard to review with that number of changes

Also resolve the merge conflicts as well

2024-04-29 17:56 UTC, yak0vliev commented on vite-project/src/App.tsx
> +  });
Lets move theme configuration in the separate file

2024-04-29 17:56 UTC, yak0vliev commented on vite-project/src/App.tsx
> +      <div className="app-container">
Use Mui `Box` instead of div, and lets drop the classNames everywhere

2024-04-29 17:56 UTC, yak0vliev commented on vite-project/src/App.tsx
> +        <div className="theme-toggle" style={{ position: 'fixed', top: '20px', right: '20px' }}>
You can use MUI `sx` prop instead of style
And try to replace all hardcoded values for styles, like "10px" or "1rem" with MUI sizings like `100`, `450` etc.
https://mui.com/system/sizing/

2024-04-29 17:56 UTC, yak0vliev commented on vite-project/src/components/Form.tsx
> +});
Why did you create one more theme here? You already have one in `App.tsx`, which is used in the `ThemeProvider`, which wraps your whole app, so you can use theme everywhere you want with `useTheme` hook

2024-04-29 17:56 UTC, yak0vliev commented on vite-project/src/components/Form.tsx
> +    <ThemeProvider theme={theme}>
And therefore you dont need one more ThemeProvider here, because it is already wraps you whole app in App.tsx

2024-04-29 17:56 UTC, yak0vliev commented on vite-project/src/components/materialUISwitch.tsx
Rename this file to something more appropriate, for example `StyledSwitch`. `StyledCOMPONENT_NAME` is always a good name for a component, in which you defined custom styles

2024-04-29 17:56 UTC, yak0vliev commented on vite-project/src/index.css
We dont really use css with MUI library, so lets drop this and every css rules in the project as well, and replace them with MUI stylings

2024-04-29 17:56 UTC, yak0vliev commented on vite-project/src/components/Card.tsx
>      </div>
Use the MUI components here instead of html tags

2024-04-29 18:45 UTC, Feevicun commented on vite-project/src/index.css
<img width="495" alt="Screenshot 2024-04-29 at 21 44 16" src="https://github.com/proga-react-practice/alpha-viktoria-osoba/assets/121824657/da90285e-58b8-47e8-a9f6-c29401427ca3">

Is it possible to write in this style or write styles in each file according to the component?

2024-04-29 19:12 UTC, yak0vliev commented on vite-project/src/index.css
Yes, potentially you can use `styled` for components like this
One more way is just to create custom component with defined styles, like you did with `Card` component

And if you are doing it with this approach, it's better to style MUI Box or Container instead of div.

2024-04-29 19:14 UTC, Feevicun commented on vite-project/src/index.css
Okey, thanks

2024-04-30 00:20 UTC, yak0vliev reviewed
Good job
REsolve the comments and merge conflicts and merge it by yourself

2024-04-30 00:20 UTC, yak0vliev commented on vite-project/src/components/style.tsx
> +  },
I dont think this styles belong to the Box, lets move them to the appropriate components

2024-05-04 16:33 UTC, merged